@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region metadata for the Communication Services resources. The service itself is global.')
param location string = 'global'

var dataLocation = context.resource.properties.dataLocation
var senderUsername = context.resource.properties.senderUsername

// Azure Communication Services Email: the email service owns the sender domain,
// and the communication service holds the access keys the application client uses.
resource emailService 'Microsoft.Communication/emailServices@2023-04-01' = {
  name: 'acsemail-${uniqueString(context.resource.id)}'
  location: location
  properties: {
    dataLocation: dataLocation
  }

  // An Azure-managed domain needs no DNS records or verification, so the
  // application can send as soon as the recipe finishes.
  resource managedDomain 'domains@2023-04-01' = {
    name: 'AzureManagedDomain'
    location: location
    properties: {
      domainManagement: 'AzureManaged'
      userEngagementTracking: 'Disabled'
    }
  }
}

resource communicationService 'Microsoft.Communication/communicationServices@2023-04-01' = {
  name: 'acs-${uniqueString(context.resource.id)}'
  location: location
  properties: {
    dataLocation: dataLocation
    linkedDomains: [
      emailService::managedDomain.id
    ]
  }
}

output result object = {
  values: {
    senderAddress: '${senderUsername}@${emailService::managedDomain.properties.mailFromSenderDomain}'
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    connectionString: communicationService.listKeys().primaryConnectionString
  }
}
